feat: add modal in new project
DO-AN-HCMUT/FE-DO-AN pull request #8
Opened 2024-05-26 12:17 UTC by vwaizer

2024-05-26 13:48 UTC, ng-ngoc-hung approved these changes

2024-05-26 14:17 UTC, ng-ngoc-hung approved these changes

2024-05-30 03:48 UTC, dlnanh85 commented on package.json
> +    "@emotion/react": "^11.11.4",
We are using TailwindCSS utility classes for styling. It's best not to introduce more CSS implementation in the project.

2024-05-30 03:57 UTC, dlnanh85 requested changes

2024-05-30 03:57 UTC, dlnanh85 commented on package.json
> +    "@emotion/styled": "^11.11.5",
We are using TailwindCSS utility classes for styling. It's best not to introduce more CSS implementation in the project.

2024-05-30 03:57 UTC, dlnanh85 commented on src/components/Header/index.tsx
> +};
Use TailwindCSS classes.

2024-05-30 03:57 UTC, dlnanh85 commented on src/components/Header/index.tsx
> +  const handleClose = () => setIsOpenModal(false);
For short event handlers (1-2 lines), it is common to put them right at the JSX, as an annonymous arrow function.

2024-05-30 03:57 UTC, dlnanh85 commented on src/components/SideBar/index.tsx
> +    <div className='h-full w-[15%] cursor-pointer border-r-[1px] border-[#ccc] px-2 py-4'>
The hover styling should not apply to the whole the sidebar `div`, but its items.

2024-06-02 01:15 UTC, ng-ngoc-hung approved these changes, later dismissed

2024-08-12 09:43 UTC, closed without merging